# БИБЛЕОТЕКА NUMPY 

##### ЗАДАНИЕ 1

In [1]:
import numpy as np

a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_a = np.array([np.mean(a[:,0]), np.mean(a[:,1])])
mean_a

array([2. , 8.4])

##### ЗАДАНИЕ 2

In [2]:
a_centered = np.subtract(a,mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

##### ЗАДАНИЕ 3

In [3]:
a_centered_sp = a_centered[:,0] @ a_centered[:,1]
a_centered_sp_cov = a_centered_sp/(a_centered.shape[0]-1)
a_centered_sp_cov

2.0

##### ЗАДАНИЕ 4*

In [4]:
cov = np.cov(a.T)
cov

array([[1. , 2. ],
       [2. , 4.3]])

### БИБЛЕОТЕКА PANDAS

##### ЗАДАНИЕ 1

In [13]:
import pandas as pd

In [6]:

authors = pd.DataFrame(
{
    'author_id': [1,2,3],
    'author_name': ['Тургенев', 'Чехов', 'Островский']
})


books  = pd.DataFrame(
{
    'author_id': [1, 1, 1, 2, 2, 3, 3],
    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    'price': [450, 300, 350, 500, 450, 370, 290]
})

##### ЗАДАНИЕ 2

In [7]:
authors_price = pd.merge(authors, books, on='author_id', how='inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

##### ЗАДАНИЕ 3

In [17]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

##### ЗАДАНИЕ 4

In [49]:

authors_stat = authors_price.groupby('author_name')
authors_stat.agg({'price':['min', 'max','mean']})



price                 
              min  max        mean
author_name                       
Островский    290  370  330.000000
Тургенев      300  450  366.666667
Чехов         450  500  475.000000

#### ЗАДАНИЕ 5**

###### не успеваю.